### ISSUE TITLE
Question: does the bytecode generator optimize the generated code?

### ISSUE THREAD

**Issue by MarcoCicognani** [koekeishiya/maji#1]
As I wrote in the title I would like to know whether the bytecode generator performs any kind of optimization for the code generation. I'm studying your project because I really like it. Keep going. Regards

**Comment by koekeishiya** [comment]
There is no optimization or anything going on. The bytecode generation is literally the dumbest thing possible - there is not even a proper register allocation scheme yet, so that what you see here with a grain of salt. If all of this is still very new to you, this project will likely be a good indicator for how to get started though.
